# Generated by Django 4.1.3 on 2022-11-16 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Тип документа"),
                ),
            ],
            options={
                "verbose_name": "Тип документа",
                "verbose_name_plural": "Тип документа",
            },
        ),
        migrations.CreateModel(
            name="Decrees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("pub_date", models.DateField(auto_now_add=True)),
                ("file", models.FileField(upload_to="decree/", verbose_name="Файл")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_decree",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decree_type",
                        to="decree.type",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книгу",
                "verbose_name_plural": "Книги",
                "ordering": ["-pub_date"],
            },
        ),
    ]
