# Generated by Django 4.1.3 on 2022-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decree", "0002_alter_decrees_options_decrees_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decrees",
            name="file",
            field=models.FileField(upload_to="decree/%Y/%m/%d/", verbose_name="Файл"),
        ),
    ]
