# Generated by Django 4.1.3 on 2022-11-17 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("decree", "0003_alter_decrees_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="decrees", name="description",),
        migrations.AddField(
            model_name="decrees",
            name="date_create",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DecreesChanged",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("number", models.IntegerField(verbose_name="Номер")),
                ("date_create", models.DateField()),
                ("pub_date", models.DateField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(upload_to="decree/%Y/%m/%d/", verbose_name="Файл"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_decree_changed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decree",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decree_changed_decree",
                        to="decree.type",
                        verbose_name="Приказ",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decree_changed_type",
                        to="decree.type",
                        verbose_name="Тип документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приказ",
                "verbose_name_plural": "Приказы",
                "ordering": ["-pub_date"],
            },
        ),
    ]
