# Generated by Django 4.1.3 on 2022-11-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("decree", "0004_remove_decrees_description_decrees_date_create_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decreeschanged",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Изменения",
                "verbose_name_plural": "Изменения",
            },
        ),
        migrations.AlterField(
            model_name="decreeschanged",
            name="decree",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decree_changed_decree",
                to="decree.decrees",
                verbose_name="Приказ",
            ),
        ),
    ]
