# Generated by Django 4.1.3 on 2022-11-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("decree", "0005_alter_decreeschanged_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decrees",
            name="decree",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_decree",
                to="decree.decrees",
            ),
            preserve_default=False,
        ),
    ]
