# Generated by Django 4.1.3 on 2022-11-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("decree", "0006_decrees_decree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decrees",
            name="decree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_decree",
                to="decree.decrees",
            ),
        ),
    ]
